{"version":3,"file":"static/webpack/static/development/pages/_error.js.b82598ac65d7df82b3df.hot-update.js","sources":["webpack:///./node_modules/next/dist/build/webpack/loaders/next-client-pages-loader.js","webpack:///./node_modules/next/error.js","webpack:///./pages/_error.js"],"sourcesContent":["\n    (window.__NEXT_P=window.__NEXT_P||[]).push([\"/_error\", function() {\n      var mod = require(\"/Users/luffyzhou/webfront/github/next-sentry-demo/pages/_error.js\")\n      if(module.hot) {\n        module.hot.accept(\"/Users/luffyzhou/webfront/github/next-sentry-demo/pages/_error.js\", function() {\n          if(!next.router.components[\"/_error\"]) return\n          var updatedPage = require(\"/Users/luffyzhou/webfront/github/next-sentry-demo/pages/_error.js\")\n          next.router.update(\"/_error\", updatedPage)\n        })\n      }\n      return mod\n    }]);\n  ","module.exports = require('./dist/pages/_error')\n","import React from 'react';\nimport Error from 'next/error';\nimport * as Sentry from '@sentry/node';\n\nconst MyError = ({ statusCode, hasGetInitialPropsRun, err }) => {\n  if (!hasGetInitialPropsRun && err) {\n    // getInitialProps is not called in case of\n    // https://github.com/zeit/next.js/issues/8592. As a workaround, we pass\n    // err via _app.js so it can be captured\n    Sentry.captureException(err);\n  }\n\n  return <Error statusCode={statusCode} />\n}\n\nMyError.getInitialProps = async ({ res, err, asPath }) => {\n  const errorInitialProps = await Error.getInitialProps({ res, err })\n\n  // Workaround for https://github.com/zeit/next.js/issues/8592, mark when\n  // getInitialProps has run\n  errorInitialProps.hasGetInitialPropsRun = true;\n\n  if (res) {\n    // Running on the server, the response object is available.\n    //\n    // Next.js will pass an err on the server if a page's `getInitialProps`\n    // threw or returned a Promise that rejected\n\n    if (res.statusCode === 404) {\n      // Opinionated: do not record an exception in Sentry for 404\n      return { statusCode: 404 };\n    }\n\n    if (err) {\n      Sentry.captureException(err);\n\n      return errorInitialProps;\n    }\n  } else {\n    // Running on the client (browser).\n    //\n    // Next.js will provide an err if:\n    //\n    //  - a page's `getInitialProps` threw or returned a Promise that rejected\n    //  - an exception was thrown somewhere in the React lifecycle (render,\n    //    componentDidMount, etc) that was caught by Next.js's React Error\n    //    Boundary. Read more about what types of exceptions are caught by Error\n    //    Boundaries: https://reactjs.org/docs/error-boundaries.html\n    if (err) {\n      Sentry.captureException(err);\n\n      return errorInitialProps;\n    }\n  }\n\n  // If this point is reached, getInitialProps was called without any\n  // information about what the error might be. This is unexpected and may\n  // indicate a bug introduced in Next.js, so record it in Sentry\n  Sentry.captureException(\n    new Error(`_error.js getInitialProps missing data at path: ${asPath}`)\n  );\n\n  return errorInitialProps;\n}\n\nexport default MyError;"],"mappings":";;;;;;;;;AAAA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;;;;;;;;;;;;;;ACZA;;;;;;;;;;;;;;;;;;;;;;;;ACAA;AACA;AACA;AACA;AACA;AAAA;AAAA;AAAA;AACA;AAAA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA;AACA;AACA;AACA;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA;AACA;AAAA;AAAA;AACA;AAFA;AACA;AAEA;AACA;AACA;AACA;AANA;AAAA;AAAA;AAAA;AACA;AADA;AAAA;AAAA;AAAA;AACA;AADA;AAeA;AAAA;AACA;AAhBA;AAAA;AAAA;AAAA;AAAA;AACA;AAkBA;AAnBA;AACA;AADA;AAAA;AAAA;AACA;AADA;AAAA;AAAA;AAAA;AAAA;AACA;AAiCA;AAlCA;AACA;AADA;AAwCA;AACA;AACA;AACA;AA3CA;AACA;AADA;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA;AACA;AAiDA;;;;;;;;;;;;;;;;A","sourceRoot":""}